AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Contact Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessContactPage'
  ContactSNSMailAddress:
    Type: String
    Default: 'your.email@sample.com'
  ContactSNSTopicName:
    Type: String
    Default: 'ServerlessContactSNSTopic'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessContactPageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName
  ContactSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref ContactSNSTopicName
      DisplayName: ContactSNSTopic
  ContactSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref ContactSNSMailAddress
      Protocol: email
      TopicArn: !Ref ContactSNSTopic
  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessContactPageFrontFunction
      CodeUri: bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'Test Front Function'
      Policies:
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessContactPageApiFunction
      CodeUri: api/bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'Test Contact Function'
      Policies:
      - SNSPublishMessagePolicy:
          TopicName: !Ref ContactSNSTopicName
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          TOPIC_ARN: !Ref ContactSNSTopic
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
